version: '3.8'

services:
  flask-shop:
    build: .
    container_name: mini-shop-app
    ports:
      - "5000:5000"  # Main Flask app
      - "9000:9000"  # AI Monitor
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=your-secret-key-change-in-production
      - PORT=5000
      - AI_MONITOR_PORT=9000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - shop-network

networks:
  shop-network:
    driver: bridge

volumes:
  logs:
    driver: local
