apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini-shop-deployment
  labels:
    app: mini-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mini-shop
  template:
    metadata:
      labels:
        app: mini-shop
    spec:
      containers:
      - name: mini-shop
        image: qasim21/working_app:v2
        ports:
        - containerPort: 5000
          name: flask-app
        - containerPort: 9000
          name: ai-monitor

