apiVersion: v1
kind: Service
metadata:
  name: mini-shop-service
  labels:
    app: mini-shop
spec:
  type: NodePort
  selector:
    app: mini-shop
  ports:
  - name: flask-app
    port: 5000
    targetPort: 5000
    nodePort: 30080
    protocol: TCP
  - name: ai-monitor
    port: 9000
    targetPort: 9000
    nodePort: 30090
    protocol: TCP

